# Generated by Django 6.0.4 on 2026-06-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='first_name',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='last_name',
            new_name='last',
        ),
    ]
